### ISSUE TITLE
Excluded working with regular expression.

### ISSUE THREAD

**Issue by marcospds** [marcospds/gulp-tasklist-run#1]
Create new method that works with regular expression on excluded tasks.

**Comment by lai32290** [comment]
Can I get this one?

**Comment by renesansz** [comment]
Hey @marcospds , I'm interested in contributing to this, but can you provide more details such as sample input and expected output? what are the limitations and such?

**Comment by marcospds** [comment]
Good evening @renesansz , take a look at the readme, there explains how the project works, basically it has three parameters, it would be better to parameterize regular expressions to select tasks and also to exclude tasks.

For example: 
```
...
TaskListRun.run(tasks, 'e2e.*', 'e2e\:\*,e2e:test.*');
...
```

**Comment by marcospds** [comment]
Select sample: https://regexr.com/4mfir
Exclude sample: https://regexr.com/4mfj4

Expected to run:
e2e:name
e2e:login
e2e:create
e2e:save

**Comment by renesansz** [comment]
noted. will check on this, thank!

**Comment by renesansz** [comment]
Submitted PR #2
